// flow-typed signature: af15c7cca26e50ce36e5cbcdd7b2eafb
// flow-typed version: <<STUB>>/fetch-polyfill_v^0.8.2/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-polyfill/fetch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-polyfill/fetch.js' {
  declare module.exports: $Exports<'fetch-polyfill/fetch'>;
}
