// flow-typed signature: e4367303e18bcdd849fe97ce178cd70e
// flow-typed version: <<STUB>>/global-jsdom_v^5.0.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'global-jsdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'global-jsdom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'global-jsdom/es' {
  declare module.exports: any;
}

declare module 'global-jsdom/es/register' {
  declare module.exports: any;
}

declare module 'global-jsdom/lib' {
  declare module.exports: any;
}

declare module 'global-jsdom/lib/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'global-jsdom/es/index' {
  declare module.exports: $Exports<'global-jsdom/es'>;
}
declare module 'global-jsdom/es/index.js' {
  declare module.exports: $Exports<'global-jsdom/es'>;
}
declare module 'global-jsdom/es/register.js' {
  declare module.exports: $Exports<'global-jsdom/es/register'>;
}
declare module 'global-jsdom/lib/index' {
  declare module.exports: $Exports<'global-jsdom/lib'>;
}
declare module 'global-jsdom/lib/index.js' {
  declare module.exports: $Exports<'global-jsdom/lib'>;
}
declare module 'global-jsdom/lib/register.js' {
  declare module.exports: $Exports<'global-jsdom/lib/register'>;
}
