// flow-typed signature: fe3ca7b9f761d257eb88184052633ce7
// flow-typed version: <<STUB>>/https-proxy-agent_v^2.2.2/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'https-proxy-agent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'https-proxy-agent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'https-proxy-agent/index' {
  declare module.exports: $Exports<'https-proxy-agent'>;
}
declare module 'https-proxy-agent/index.js' {
  declare module.exports: $Exports<'https-proxy-agent'>;
}
