// flow-typed signature: 5e09603fabd1a102a7c1c5c96bd9c63f
// flow-typed version: <<STUB>>/isbn_vgit+https://github.com/AV-Forlaget/isbnjs.git#master/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isbn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isbn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isbn/isbn-groups' {
  declare module.exports: any;
}

declare module 'isbn/isbn' {
  declare module.exports: any;
}

declare module 'isbn/tests/lib/test/tiny' {
  declare module.exports: any;
}

declare module 'isbn/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isbn/isbn-groups.js' {
  declare module.exports: $Exports<'isbn/isbn-groups'>;
}
declare module 'isbn/isbn.js' {
  declare module.exports: $Exports<'isbn/isbn'>;
}
declare module 'isbn/tests/lib/test/tiny.js' {
  declare module.exports: $Exports<'isbn/tests/lib/test/tiny'>;
}
declare module 'isbn/tests/tests.js' {
  declare module.exports: $Exports<'isbn/tests/tests'>;
}
