// flow-typed signature: edeb2c8377ac50fbdaff13936efb6254
// flow-typed version: <<STUB>>/karma-webpack_v^4.0.2/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-webpack/dist' {
  declare module.exports: any;
}

declare module 'karma-webpack/dist/karma-webpack' {
  declare module.exports: any;
}

declare module 'karma-webpack/dist/mocha-env-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-webpack/dist/index' {
  declare module.exports: $Exports<'karma-webpack/dist'>;
}
declare module 'karma-webpack/dist/index.js' {
  declare module.exports: $Exports<'karma-webpack/dist'>;
}
declare module 'karma-webpack/dist/karma-webpack.js' {
  declare module.exports: $Exports<'karma-webpack/dist/karma-webpack'>;
}
declare module 'karma-webpack/dist/mocha-env-loader.js' {
  declare module.exports: $Exports<'karma-webpack/dist/mocha-env-loader'>;
}
