// flow-typed signature: 166f0ef0fed3a4c42171d27c5f4fc0da
// flow-typed version: <<STUB>>/karma-jsdom-launcher_v^7.1.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-jsdom-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-jsdom-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-jsdom-launcher/test/native-jsdom-options-test' {
  declare module.exports: any;
}

declare module 'karma-jsdom-launcher/test/no-provided-config-test' {
  declare module.exports: any;
}

declare module 'karma-jsdom-launcher/test/simple-dom-manipulation-test' {
  declare module.exports: any;
}

declare module 'karma-jsdom-launcher/test/test-helper/child_process' {
  declare module.exports: any;
}

declare module 'karma-jsdom-launcher/test/test-helper/fs' {
  declare module.exports: any;
}

declare module 'karma-jsdom-launcher/test/test-helper' {
  declare module.exports: any;
}

declare module 'karma-jsdom-launcher/test/test-helper/intercept_stdout' {
  declare module.exports: any;
}

declare module 'karma-jsdom-launcher/test/test-helper/jsdom-version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-jsdom-launcher/index' {
  declare module.exports: $Exports<'karma-jsdom-launcher'>;
}
declare module 'karma-jsdom-launcher/index.js' {
  declare module.exports: $Exports<'karma-jsdom-launcher'>;
}
declare module 'karma-jsdom-launcher/test/native-jsdom-options-test.js' {
  declare module.exports: $Exports<'karma-jsdom-launcher/test/native-jsdom-options-test'>;
}
declare module 'karma-jsdom-launcher/test/no-provided-config-test.js' {
  declare module.exports: $Exports<'karma-jsdom-launcher/test/no-provided-config-test'>;
}
declare module 'karma-jsdom-launcher/test/simple-dom-manipulation-test.js' {
  declare module.exports: $Exports<'karma-jsdom-launcher/test/simple-dom-manipulation-test'>;
}
declare module 'karma-jsdom-launcher/test/test-helper/child_process.js' {
  declare module.exports: $Exports<'karma-jsdom-launcher/test/test-helper/child_process'>;
}
declare module 'karma-jsdom-launcher/test/test-helper/fs.js' {
  declare module.exports: $Exports<'karma-jsdom-launcher/test/test-helper/fs'>;
}
declare module 'karma-jsdom-launcher/test/test-helper/index' {
  declare module.exports: $Exports<'karma-jsdom-launcher/test/test-helper'>;
}
declare module 'karma-jsdom-launcher/test/test-helper/index.js' {
  declare module.exports: $Exports<'karma-jsdom-launcher/test/test-helper'>;
}
declare module 'karma-jsdom-launcher/test/test-helper/intercept_stdout.js' {
  declare module.exports: $Exports<'karma-jsdom-launcher/test/test-helper/intercept_stdout'>;
}
declare module 'karma-jsdom-launcher/test/test-helper/jsdom-version.js' {
  declare module.exports: $Exports<'karma-jsdom-launcher/test/test-helper/jsdom-version'>;
}
