// flow-typed signature: 8c89af96cced20d4a0925ce840c1c224
// flow-typed version: <<STUB>>/postcss-color-rebeccapurple_v^4.0.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-color-rebeccapurple'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-color-rebeccapurple' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-color-rebeccapurple/index' {
  declare module.exports: $Exports<'postcss-color-rebeccapurple'>;
}
declare module 'postcss-color-rebeccapurple/index.js' {
  declare module.exports: $Exports<'postcss-color-rebeccapurple'>;
}
