// flow-typed signature: 0a00ae6f9c454273cec905a9f6ce1182
// flow-typed version: <<STUB>>/react-spinners_v^0.6.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spinners'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spinners' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spinners/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/colors' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/proptypes' {
  declare module.exports: any;
}

declare module 'react-spinners/interfaces' {
  declare module.exports: any;
}

declare module 'react-spinners/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SyncLoader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spinners/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/BarLoader'>;
}
declare module 'react-spinners/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/BeatLoader'>;
}
declare module 'react-spinners/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/BounceLoader'>;
}
declare module 'react-spinners/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/CircleLoader'>;
}
declare module 'react-spinners/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/ClimbingBoxLoader'>;
}
declare module 'react-spinners/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/ClipLoader'>;
}
declare module 'react-spinners/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/DotLoader'>;
}
declare module 'react-spinners/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/FadeLoader'>;
}
declare module 'react-spinners/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/GridLoader'>;
}
declare module 'react-spinners/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/HashLoader'>;
}
declare module 'react-spinners/helpers/colors.js' {
  declare module.exports: $Exports<'react-spinners/helpers/colors'>;
}
declare module 'react-spinners/helpers/index' {
  declare module.exports: $Exports<'react-spinners/helpers'>;
}
declare module 'react-spinners/helpers/index.js' {
  declare module.exports: $Exports<'react-spinners/helpers'>;
}
declare module 'react-spinners/helpers/proptypes.js' {
  declare module.exports: $Exports<'react-spinners/helpers/proptypes'>;
}
declare module 'react-spinners/index' {
  declare module.exports: $Exports<'react-spinners'>;
}
declare module 'react-spinners/index.js' {
  declare module.exports: $Exports<'react-spinners'>;
}
declare module 'react-spinners/interfaces.js' {
  declare module.exports: $Exports<'react-spinners/interfaces'>;
}
declare module 'react-spinners/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/MoonLoader'>;
}
declare module 'react-spinners/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/PacmanLoader'>;
}
declare module 'react-spinners/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/PropagateLoader'>;
}
declare module 'react-spinners/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/PulseLoader'>;
}
declare module 'react-spinners/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/RingLoader'>;
}
declare module 'react-spinners/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/RiseLoader'>;
}
declare module 'react-spinners/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/RotateLoader'>;
}
declare module 'react-spinners/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/ScaleLoader'>;
}
declare module 'react-spinners/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/SkewLoader'>;
}
declare module 'react-spinners/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/SquareLoader'>;
}
declare module 'react-spinners/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/SyncLoader'>;
}
