// flow-typed signature: f5f4aabc512b50e782393bf5e2616e0c
// flow-typed version: <<STUB>>/string-replace-webpack-plugin_v^0.1.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-replace-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-replace-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'string-replace-webpack-plugin/loader' {
  declare module.exports: any;
}

declare module 'string-replace-webpack-plugin/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'string-replace-webpack-plugin/index' {
  declare module.exports: $Exports<'string-replace-webpack-plugin'>;
}
declare module 'string-replace-webpack-plugin/index.js' {
  declare module.exports: $Exports<'string-replace-webpack-plugin'>;
}
declare module 'string-replace-webpack-plugin/loader.js' {
  declare module.exports: $Exports<'string-replace-webpack-plugin/loader'>;
}
declare module 'string-replace-webpack-plugin/test.js' {
  declare module.exports: $Exports<'string-replace-webpack-plugin/test'>;
}
