// flow-typed signature: 323964f1680255237e1da51c02d32724
// flow-typed version: <<STUB>>/wikitext-dom_v0.0.7/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wikitext-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wikitext-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wikitext-dom/karma.conf' {
  declare module.exports: any;
}

declare module 'wikitext-dom/lib/wikitext-dom' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src/Comment' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src/Container' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src/Extension' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src/extensions/Timeline' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src/Header' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src/Ignore' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src/Parser' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src/Root' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src/Template' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src/TemplateArgument' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src/TextNode' {
  declare module.exports: any;
}

declare module 'wikitext-dom/src/WikiDomNode' {
  declare module.exports: any;
}

declare module 'wikitext-dom/test/ContainerTest' {
  declare module.exports: any;
}

declare module 'wikitext-dom/test/extensions/TimelineTest' {
  declare module.exports: any;
}

declare module 'wikitext-dom/test/globals' {
  declare module.exports: any;
}

declare module 'wikitext-dom/test/ParserTest' {
  declare module.exports: any;
}

declare module 'wikitext-dom/test/TemplateArgumentTest' {
  declare module.exports: any;
}

declare module 'wikitext-dom/test/TemplateTest' {
  declare module.exports: any;
}

declare module 'wikitext-dom/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wikitext-dom/karma.conf.js' {
  declare module.exports: $Exports<'wikitext-dom/karma.conf'>;
}
declare module 'wikitext-dom/lib/wikitext-dom.js' {
  declare module.exports: $Exports<'wikitext-dom/lib/wikitext-dom'>;
}
declare module 'wikitext-dom/src/Comment.js' {
  declare module.exports: $Exports<'wikitext-dom/src/Comment'>;
}
declare module 'wikitext-dom/src/Container.js' {
  declare module.exports: $Exports<'wikitext-dom/src/Container'>;
}
declare module 'wikitext-dom/src/Extension.js' {
  declare module.exports: $Exports<'wikitext-dom/src/Extension'>;
}
declare module 'wikitext-dom/src/extensions/Timeline.js' {
  declare module.exports: $Exports<'wikitext-dom/src/extensions/Timeline'>;
}
declare module 'wikitext-dom/src/Header.js' {
  declare module.exports: $Exports<'wikitext-dom/src/Header'>;
}
declare module 'wikitext-dom/src/Ignore.js' {
  declare module.exports: $Exports<'wikitext-dom/src/Ignore'>;
}
declare module 'wikitext-dom/src/index' {
  declare module.exports: $Exports<'wikitext-dom/src'>;
}
declare module 'wikitext-dom/src/index.js' {
  declare module.exports: $Exports<'wikitext-dom/src'>;
}
declare module 'wikitext-dom/src/Parser.js' {
  declare module.exports: $Exports<'wikitext-dom/src/Parser'>;
}
declare module 'wikitext-dom/src/Root.js' {
  declare module.exports: $Exports<'wikitext-dom/src/Root'>;
}
declare module 'wikitext-dom/src/Template.js' {
  declare module.exports: $Exports<'wikitext-dom/src/Template'>;
}
declare module 'wikitext-dom/src/TemplateArgument.js' {
  declare module.exports: $Exports<'wikitext-dom/src/TemplateArgument'>;
}
declare module 'wikitext-dom/src/TextNode.js' {
  declare module.exports: $Exports<'wikitext-dom/src/TextNode'>;
}
declare module 'wikitext-dom/src/WikiDomNode.js' {
  declare module.exports: $Exports<'wikitext-dom/src/WikiDomNode'>;
}
declare module 'wikitext-dom/test/ContainerTest.js' {
  declare module.exports: $Exports<'wikitext-dom/test/ContainerTest'>;
}
declare module 'wikitext-dom/test/extensions/TimelineTest.js' {
  declare module.exports: $Exports<'wikitext-dom/test/extensions/TimelineTest'>;
}
declare module 'wikitext-dom/test/globals.js' {
  declare module.exports: $Exports<'wikitext-dom/test/globals'>;
}
declare module 'wikitext-dom/test/ParserTest.js' {
  declare module.exports: $Exports<'wikitext-dom/test/ParserTest'>;
}
declare module 'wikitext-dom/test/TemplateArgumentTest.js' {
  declare module.exports: $Exports<'wikitext-dom/test/TemplateArgumentTest'>;
}
declare module 'wikitext-dom/test/TemplateTest.js' {
  declare module.exports: $Exports<'wikitext-dom/test/TemplateTest'>;
}
declare module 'wikitext-dom/webpack.config.js' {
  declare module.exports: $Exports<'wikitext-dom/webpack.config'>;
}
